### ISSUE TITLE
Run selection is often behind

### ISSUE THREAD

**Issue by ngharrison** [apommel/vscode-matlab-interactive-terminal#12] opened 2020-04-25 20:07 UTC
The run selection option sometimes seems to be one selection behind. It takes two (maybe more?) runs to run what I selected. The first attempt re-runs what was previously selected. I don't know the details but it might have to do with how temp.m is updated?

Unsure if this is related to #9.

**Comment by apommel** [comment] 2020-04-26 05:02
I could not reproduce, but yes I think it can definitely happen with how temp files are managed. I tried to make it a bit more resilient in the latest release that just went live. Could you tell me if it fixed this issue for you?

**Comment by ngharrison** [comment] 2020-04-29 00:44
I updated to the newest version and I'm still seeing the same behavior. I haven't yet checked with other extensions disabled.

**Comment by aidedinertial** [comment] 2020-07-29 20:26
I am also experiencing this issue.

**Comment by weihongliang233** [comment] 2020-08-04 20:53
I encountered the same problem, and I have done some experiments to see what's the cause. 

Every time I run the selection, the Matlab REPL execute the temp.m as mentioned above. And I treid to open the temp.m file, modify it save it. Something unexpected happened: the result is still behind the modification. For example, the previous content is "a=100" , and I overwrite it to "a=300" and the result is 100. Run it again and I gained the correct result 300. 

However, when I do the same thing in the real MATLAB command line, everything works well.

**Comment by weihongliang233** [comment] 2020-08-09 11:56
Add a `clear functions` to the command `runMlSelection` like `runMlScript` does. This method works for me, and a pull request has been created.

**Comment by apommel** [comment] 2020-08-10 03:28
Thank you, I'll release a new version including the fix as soon as possible. Once it's done I'll close this if it works for everyone.

**Comment by apommel** [comment] 2020-10-11 12:55
Fixed with 0.3.3 release

**Closed by apommel** 2020-10-11 12:55 UTC
